apiVersion: v1
kind: Service
metadata:
  name: {{ include "cnpj-pipeline.fullname" . }}-dagster
  labels:
    {{- include "cnpj-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: dagster
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.dagster.webserverPort }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    {{- include "cnpj-pipeline.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dagster-webserver
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cnpj-pipeline.fullname" . }}-mlflow
  labels:
    {{- include "cnpj-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mlflow.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "cnpj-pipeline.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
