apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cnpj-pipeline.fullname" . }}-dagster-webserver
  labels:
    {{- include "cnpj-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: dagster-webserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cnpj-pipeline.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dagster-webserver
  template:
    metadata:
      labels:
        {{- include "cnpj-pipeline.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dagster-webserver
    spec:
      containers:
        - name: dagster-webserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3001", "-w", "/app/dagster.yaml"]
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:{{ .Values.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
