apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpj-pipeline.fullname" . }}-secret
  labels:
    {{- include "cnpj-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  S3_ACCESS_KEY: {{ "minioadmin" | b64enc | quote }}
  S3_SECRET_KEY: {{ "minioadmin" | b64enc | quote }}
